Actually fix `java.lang.NoSuchMethodError` for Bridgeless (#41081)
Summary:
Pull Request resolved: https://github.com/facebook/react-native/pull/41081

It turns out that Bridgeless for RN-Tester release is still broken.
This fixes it by making sure we actually `DoNotStrip` the missing constructor

Changelog:
[Android] [Fixed] - Fix crash with `java.lang.NoSuchMethodError` for Bridgeless

Reviewed By: RSNara

Differential Revision: D50455967

fbshipit-source-id: eae971fceeb863d8a400e9de1d2467637d59d2b0